
DROP SEQUENCE UPLOAD_FILES_SEQ;
DROP TRIGGER UPLOAD_FILES_AUTO_INCR_TRI;
DROP TABLE UPLOAD_FILES PURGE;

CREATE TABLE UPLOAD_FILES 
(
  FILE_ID NUMBER NOT NULL 
, OLD_NAME VARCHAR2(216) NOT NULL 
, SAVE_PATH VARCHAR2(216) NOT NULL 
, REAL_NAME VARCHAR(216) NOT NULL
, FILE_SIZE NUMBER NOT NULL 
, FILE_TYPE VARCHAR2(50) NOT NULL 
, FILE_DESC VARCHAR2(20) 
, UPLOAD_USER VARCHAR2(20) NOT NULL 
, UPLOAD_DATE TIMESTAMP（6） default SYSTIMESTAMP
, CONSTRAINT UPLOAD_FILES_PK PRIMARY KEY 
  (
    FILE_ID 
  )
  ENABLE 
, CONSTRAINT UPLOAD_USER_FK FOREIGN KEY(UPLOAD_USER) 
  REFERENCES BookUsers(userName) ON DELETE CASCADE
);


CREATE SEQUENCE UPLOAD_FILES_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER UPLOAD_FILES_AUTO_INCR_TRI
BEFORE INSERT ON UPLOAD_FILES
FOR EACH ROW
BEGIN
  :new.file_id := UPLOAD_FILES_SEQ.nextVal();
END;
/
COMMIT;


