
DROP TRIGGER USER_ID_AUTO_INCREMENT_TRIGGER;
DROP SEQUENCE USER_ID_SEQ;
DROP TABLE USERS PURGE;

CREATE TABLE USERS 
(
  ID NUMBER NOT NULL 
, USER_NAME VARCHAR2(25 BYTE) NOT NULL 
, PASSWORD VARCHAR2(25 BYTE) NOT NULL 
, PHONE_NUM VARCHAR2(11 BYTE) 
, ADDRESS VARCHAR2(30 BYTE) 
, REGISTER_DATE DATE 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
); 

CREATE  SEQUENCE USER_ID_SEQ 
INCREMENT BY 1
START WITH 1;


CREATE OR REPLACE TRIGGER USER_ID_AUTO_INCREMENT_TRIGGER
BEFORE INSERT ON Users
FOR EACH ROW
BEGIN
  :new.id  := USER_ID_SEQ.nextVal();
END;
/


INSERT INTO USERS(USER_NAME,PASSWORD,PHONE_NUM,ADDRESS,REGISTER_DATE)
VALUES('DAVID','1234567','18070500090','JX',SYSDATE);

INSERT INTO USERS(user_name,password,phone_num,address,register_date)
VALUES('Black','88888888','17605089995','CHINA',SYSDATE);

INSERT INTO USERS(user_name,password,phone_num,address,register_date)
VALUES('Black-TD','76123141','17628361921','LOS',SYSDATE);
COMMIT;





SELECT * FROM USERS;